### ISSUE TITLE
ControlFrame issues

### ISSUE THREAD

**Issue by eduzal** [sojamo/controlp5#138]
hello.

first of all, the ControlP5Frames example is not working. I've tried it in processing 3.3.7 and 3.4.
lines 70 and 71
```
f.add( p );
p.init();
```
It returns
`The funcntion "add()" expects parameters like:"add(Component)"`

also i'm having other problems using ControlFrames.
I have a simple particlesystem under a boolean controlled by a toggle. the intention is to clear the particle system when it's toggled off.

```
if (isRing) {
    if (frameCount%30==0) r.addRing();
    r.display();
  }
```
in my Control Frame setup() i have the toggle
```
 cp5.addToggle("ringToggle")
      .setPosition(160, 50)
      .setSize(80, 80)
      .setValue(false)
      ;
```
and it's function
```
  void ringToggle(boolean toggle) {
    if (toggle==true) {
      isRing=true;
    } else {
      isRing=false;
      
      r.rings.clear();
      //for (int i=0; i<r.rings.size(); i++) {
      //  Ring ri=r.rings.get(i);
      //  r.rings.remove(ri);
      //}
    }
  }
```
it crashes and returns me
```
Sep 20, 2018 1:24:32 PM controlP5.ControlBroadcaster printMethodError
SEVERE: An error occured while forwarding a Controller event, please check your code at ringToggle
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
	at controlP5.ControlBroadcaster.callTarget(Unknown Source)
	at controlP5.ControlBroadcaster.broadcast(Unknown Source)
	at controlP5.Controller.broadcast(Unknown Source)
	at controlP5.Toggle.setState(Unknown Source)
	at controlP5.Toggle.setValue(Unknown Source)
	at controlP5.Toggle.setValue(Unknown Source)
	at dome_004$ControlFrame.setup(dome_004.java:356)
	at processing.core.PApplet.handleDraw(PApplet.java:2404)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
Caused by: java.lang.NullPointerException
	at dome_004$ControlFrame.ringToggle(dome_004.java:467)
	... 15 more
```

it might be better explained here
[https://discourse.processing.org/t/clearing-an-arraylist/3697](url)

**Comment by sojamo** [comment]
there was a discussion in issue #17 regarding controlFrames and why they don't work with 3.x anymore. at the end of the thread you will find a link to a [forum discussion](https://forum.processing.org/two/discussion/13446/events-with-two-windows-using-controlp5-processing-3) and an example that demonstrates how to use a ControlFrame with 3.x (works for me using controlP5 2.2.6 and Processing 3.4) – see last post.

The error you are mentioning might not be related to controlP5. Here I suspect that `r` or `r.rings` might not be created yet or null when ringToggle is called? To better evaluate this issue, a working example that demonstrating this behaviour would be useful.

**Comment by eduzal** [comment]
Hi sojamo.
I'm already using the solutions presented on the forum discussion that you published. Usually it works fine. I only have trouble with clearing arraylists inside objects, it happens with bangs, also with buttons.
In the thread at the forum a fix was proposed, instantiating the ControlFrame for last at the main setup. It works till a certain time, then it crashes, it  clears the array, but in the memory it still keeps the size of the eraded arrayList.
I have found a solution in the main draw function to stop generating particles and let the array empty itself, but it keeps running.

```
  if (isRing) {
    if (frameCount%30==0) r.addRing();
  }
  r.display();
```
and this is the constructor for the ControlFrame object
```
  public ControlFrame(PApplet _parent, int _w, int _h, String _name, int _oW, int _oH) {
    super();   
    parent = _parent;
    w=_w;
    h=_h;
    PApplet.runSketch(new String[]{this.getClass().getName()}, this);
    oW=_oW;
    oH=_oH;
  }
```

**Comment by sojamo** [comment]
this is probably a concurrency issue. there are 2 threads running, the sketch itself and the ControlFrame. 

Without having access to the code of a running example that demonstrates the behaviour you are encountering it is hard for me to tell if this is a controlp5 issue or a sketch issue. However if you modify an array in your main sketch from the controlFrame, a concurrency issue is very likely. 

Using a [CopyOnWriteArrayList](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) instead of ArrayList might solve that issue.

Looking at the error message you posted earlier in your first post, it says there is a NullPointerException

> Caused by: java.lang.NullPointerException
	at dome_004$ControlFrame.ringToggle(dome_004.java:467)

it might be the case that r is not yet instantiated when ringToggle is called and throws that exception?

**Comment by sojamo** [comment]
@eduzal it seems you have fixed your issue in the processing forum [Clearing an ArrayList](https://discourse.processing.org/t/clearing-an-arraylist/3697). can this issue be closed here?

**Comment by eduzal** [comment]
hi. it's quite not closed, i just haven't had the time to answer, since i had this fulldome presentation on past sunday and had to build a workaround for the presentation. and exactly that's the whole point of this thread. I created controller functions in the main thread and toggle updated these functions states. also i got some errors in sliders with callback functions, since i should only get transformations in arrayLists sizes only when sliders were RELEASED_OUTSIDE.
i built a system and used controlp5 as my gui. the whole issue roams around the paralel thread and having the ControlFrame controling the main thread. I believe that in the long run i should change the strategy completely, having the UI in the main thead, having the image produced in an PGraphics, show a preview in another surface and send it outside through syphon or another fullscreen interface.
it's kinda complex to publish it here since only the ControlFrame.pde has 970 lines. i will upload the code to github and publish the url here.

**Comment by sojamo** [comment]
just to recap 
1. the ControlFrames example does not work with Processing 3.3.7 and 3.4 this issue has been discussed #17 to fix this the example needs to be updated
2. the error message you are reporting in your first post has been further discussed on the [Processing forum](https://discourse.processing.org/t/clearing-an-arraylist/3697) and the solutions given have fixed your issue according to your last post there? 
3. The concurrency issue that occurs with ControlFrame has been addressed above
4. you are reporting new issues with callbacks, is this related to ControlFrame?
5. you are considering an alternative UI solution for your project without using ControlFrame

Issues with ControlFrame have been addressed and noted. Example needs to be updated, concurrency issues require review and possibly library changes applied to future library versions.

**Comment by eduzal** [comment]
hi andreas

here is the github link for the full sketch

https://github.com/eduzal/DomeProjection

**Comment by sojamo** [comment]
hi @eduzal thanks for sharing, looks like ti worked out in the end.
