### ISSUE TITLE
New JSON properties save and load not working

### ISSUE THREAD

**Issue by w4nderlust** [sojamo/controlp5#29]
I have a Processing 2 project and trying to port it to Processing 3.
It heavily uses p5 for parameters adjustment. In Processing 2 it works perfectly, in Processing 3 it doesn't.

The project can be found here:
https://github.com/w4nderlust/SkolpTiles

the code for loading and saving the parameters is the following:

```
void load() {
  selectInput("Select a parameters file to load", "load_callback");
}

void load_callback(File selection) {
  if (selection != null) {
    cp5.loadProperties(selection.getAbsolutePath());
    generate();
  }
}

void save() {
  selectOutput("Select a parameters file to save to", "save_callback");
}

void save_callback(File selection) {
  if (selection != null) {
    cp5.saveProperties(selection.getAbsolutePath());
  }
}
```

**Comment by w4nderlust** [comment]
Any news about this Andreas? Can I help you in any way, maybe trying to isolate the problem more?

**Comment by sojamo** [comment]
Hi, sorry for not following up earlier. the default properties format changed from .ser to JSON. Do add the following line after you have created an instance of ControlP5 to set the properties format to .ser

`cp5.getProperties().setFormat(ControlP5.SERIALIZED);`

**Comment by w4nderlust** [comment]
Your suggestion actually solved my problem, but didn't solve the problem in general.
The point is: I don't care about saving in .ser or .json as long as it works.
Right now (you can see my last push in the repo) adding your suggestion right after initializing the cp5 object worked well, and now I can save and load in .ser without problems.
But without it, after updating to Processing 3.0.1 saving and loading in .json, the controls are not updated correctly and I get the following error:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at processing.core.PApplet.selectCallback(PApplet.java:6443)
	at processing.core.PApplet.access$0(PApplet.java:6436)
	at processing.core.PApplet$3.run(PApplet.java:6348)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at controlP5.ControlP5.invoke(Unknown Source)
	at controlP5.ControllerProperties$JSONFormat.load(Unknown Source)
	at controlP5.ControllerProperties.load(Unknown Source)
	at controlP5.ControlP5.loadProperties(Unknown Source)
	at SkolpTiles.load_callback(SkolpTiles.java:1210)
	... 21 more
```

You may try yourself cloning my repository and commenting line 93 and changing line 1191 to:

      if (selection != null) {

**Comment by sojamo** [comment]
if the serialized format works for you, why not stick to it? I am aware of the error thrown when saving in JSON. Arrays are not saved properly, this affects for example the properties of a range and saves its values wrongly. I am aware of this bug and will attend to it.

**Comment by w4nderlust** [comment]
I will stick to it :) just pointing out that, even if my issue is solved there's still a bug somewhere. Thanks for your help anyway!

**Comment by kroeder** [comment]
Are there any updates regarding this issue?

**Comment by sojamo** [comment]
no updates yet.

**Comment by jshaw** [comment]
Thanks, @sojamo for suggesting switching the format to serialized, helped get my group controllers loading as needed!

**Comment by potential-difference** [comment]
Likewise - was having huge issues with radiobuttons and dropdown lists, serialized has solved this super simply!!
