### ISSUE TITLE
IndexOutOfBounds in ScrollableList and Listbox

### ISSUE THREAD

**Issue by Roysten** [sojamo/controlp5#3]
When the ScrollableList and the Listbox do not have enough items to fill the entire height of the controller, clicking below the last item causes the following stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at controlP5.ScrollableList.onRelease(Unknown Source)
	at controlP5.Controller.setMousePressed(Unknown Source)
	at controlP5.ControllerGroup.setMousePressed(Unknown Source)
	at controlP5.ControlWindow.mouseReleasedEvent(Unknown Source)
	at controlP5.ControlWindow.mouseEvent(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1236)
	at processing.core.PApplet.handleMethods(PApplet.java:1431)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2826)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2725)
	at processing.core.PApplet.handleDraw(PApplet.java:2397)
	at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
	at processing.core.PApplet.run(PApplet.java:2256)
	at java.lang.Thread.run(Unknown Source)
```
This can be easily recreated by opening the ScrollableList example, deleting all items from the list except 'a', and clicking directly below item 'a' (where the following item would be). Problems experienced in version 2.2.4.

Easy fix would be to check the length of the list before accessing, I could change this myself but I'm not aware of the consequences this might have.

**Comment by sojamo** [comment]
thanks for reporting, has been fixed inside controlP5.ScrollableList.java, the .zip that comes with release 2.2.4 has been updated as well.

**Comment by Roysten** [comment]
Awesome, that's what I call quick service :+1:

**Comment by hector-buga** [comment]
I got the same issue with the 2.2.6 version :(
